#!/usr/bin/env python3
"""
MathsLMS PDF Generator — converts curriculum JSONs + problem sets into:
- Lesson Plans (concept explanations, worked examples, GIF references)
- Worksheets (practice problems with space for working)
- Answer Keys (problems with full solutions)

Usage: python3 generate_pdfs.py [unit]
  If unit omitted, generates PDFs for ALL completed units.
"""

import json, os, glob, sys, textwrap
from fpdf import FPDF
from datetime import datetime

CONTENT_DIR = "/opt/data/.hermes/content"
OUTPUT_DIR = "/opt/data/.hermes/content/pdfs"
DB_PATH = "/opt/data/.hermes/mathlms.db"

# Colors
PRIMARY = (124, 58, 237)    # violet/purple
SECONDARY = (6, 182, 212)   # cyan
DARK = (15, 15, 26)         # dark bg
LIGHT = (243, 244, 246)     # light text bg
ACCENT_GREEN = (52, 211, 153)
ACCENT_ORANGE = (251, 146, 60)
ACCENT_RED = (239, 68, 68)

DIFFICULTY_COLORS = {
    "F": (52, 211, 153),    # green - foundation
    "C": (96, 165, 250),    # blue - core
    "H": (251, 146, 60),    # orange - challenge
    "X": (239, 68, 68),     # red - extension
}

DIFFICULTY_LABELS = {"F": "Foundation", "C": "Core", "H": "Challenge", "X": "Extension"}

class MathsLMS_PDF(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=20)
        # Add Unicode font (DejaVuSans)
        self.add_font("DejaVu", "", "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", uni=True)
        self.add_font("DejaVu", "B", "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", uni=True)
        self.add_font("DejaVu", "I", "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", uni=True)

    def header(self):
        if self.page_no() > 1:
            self.set_font("DejaVu", "I", 8)
            self.set_text_color(*SECONDARY)
            self.cell(0, 5, "MathsLMS — IGCSE Mathematics", align="L")
            self.cell(0, 5, f"Page {self.page_no()}", align="R", new_x="LMARGIN", new_y="NEXT")
            self.line(10, 12, 200, 12)
            self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("DejaVu", "I", 7)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Generated by MathsLMS — {datetime.now().strftime('%Y-%m-%d %H:%M')}", align="C")

    def chapter_title(self, title, subtitle=""):
        self.set_font("DejaVu", "B", 18)
        self.set_text_color(*PRIMARY)
        self.cell(0, 12, title, new_x="LMARGIN", new_y="NEXT")
        if subtitle:
            self.set_font("DejaVu", "", 10)
            self.set_text_color(100, 100, 120)
            self.cell(0, 8, subtitle, new_x="LMARGIN", new_y="NEXT")
        self.ln(4)
        # Accent line
        self.set_draw_color(*PRIMARY)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def section_title(self, title):
        self.set_font("DejaVu", "B", 13)
        self.set_text_color(*SECONDARY)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def body_text(self, text):
        self.set_font("DejaVu", "", 10)
        self.set_text_color(30, 30, 50)
        self.multi_cell(0, 5.5, text)
        self.ln(2)

    def bullet_point(self, text, indent=10):
        self.set_font("DejaVu", "", 10)
        self.set_text_color(30, 30, 50)
        x = self.get_x()
        self.cell(indent, 5.5, "")
        self.set_font("DejaVu", "", 10)
        self.cell(5, 5.5, "• ")
        self.multi_cell(0, 5.5, text)
        self.ln(1)

    def problem_card(self, problem, index):
        diff = problem.get("difficulty", "F")
        color = DIFFICULTY_COLORS.get(diff, (100, 100, 100))
        label = DIFFICULTY_LABELS.get(diff, "Unknown")
        marks = problem.get("marks", 1)

        # Problem header
        self.set_fill_color(*color)
        self.set_text_color(255, 255, 255)
        self.set_font("DejaVu", "B", 9)
        self.cell(12, 7, f"  {diff}", fill=True, align="C")
        self.set_fill_color(230, 230, 240)
        self.set_text_color(60, 60, 80)
        self.set_font("DejaVu", "", 8)
        self.cell(60, 7, f"  {label}", fill=True)
        self.cell(0, 7, f"  [{marks} mark{'s' if marks > 1 else ''}]", fill=True, align="R", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

        # Problem text
        self.set_font("DejaVu", "", 10)
        self.set_text_color(20, 20, 30)
        q_text = problem.get("problem_text", "")
        # Strip LaTeX delimiters for PDF readability
        q_text = q_text.replace("$$", "").replace("$", "")
        self.multi_cell(0, 5.5, f"Q{index}. {q_text}")
        
        # Space for working
        working_space = 25
        if diff in ("H", "X"):
            working_space = 35
        for _ in range(working_space // 6):
            self.set_draw_color(220, 220, 230)
            self.line(10, self.get_y(), 200, self.get_y())
            self.ln(6)

        # Answer line
        self.ln(2)
        self.set_draw_color(*color)
        self.set_line_width(0.3)
        self.dashed_line(10, self.get_y(), 200, self.get_y(), 3, 3)
        self.ln(4)

    def solution_card(self, problem, index):
        diff = problem.get("difficulty", "F")
        color = DIFFICULTY_COLORS.get(diff, (100, 100, 100))
        label = DIFFICULTY_LABELS.get(diff, "Unknown")
        
        # Header
        self.set_fill_color(*color)
        self.set_text_color(255, 255, 255)
        self.set_font("DejaVu", "B", 9)
        self.cell(12, 7, f"  {diff}", fill=True, align="C")
        self.set_fill_color(230, 230, 240)
        self.set_text_color(60, 60, 80)
        self.set_font("DejaVu", "", 8)
        ans = problem.get('answer', '')
        if not isinstance(ans, str):
            ans = str(ans)
        self.cell(0, 7, f"  {label}  —  Answer: {ans[:80]}", fill=True, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

        # Solution
        self.set_font("DejaVu", "", 9)
        self.set_text_color(30, 30, 50)
        sol = problem.get("solution", "")
        sol = sol.replace("$$", "").replace("$", "")
        self.multi_cell(0, 5, sol)
        self.ln(3)

        # Separator
        self.set_draw_color(200, 200, 210)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

    def lesson_plan_section(self, topic):
        """Render a lesson plan page for a topic."""
        sections = topic.get("sections", {})
        
        # Hook
        self.section_title("Hook")
        self.body_text(sections.get("hook", ""))

        # Prerequisites
        prereqs = sections.get("prerequisites", [])
        if prereqs:
            self.section_title("Prerequisites")
            for p in prereqs:
                self.bullet_point(p)

        # Core Explanation
        self.section_title("Core Explanation")
        core = sections.get("core_explanation", "")
        core = core.replace("$$", "").replace("$", "")
        self.body_text(core)

        # Worked Example
        we = sections.get("worked_example", "")
        if we:
            self.section_title("Worked Example")
            we = we.replace("$$", "").replace("$", "")
            self.set_fill_color(240, 245, 255)
            self.set_draw_color(180, 200, 240)
            y_before = self.get_y()
            self.body_text(we)
            # Box around worked example
            self.set_fill_color(240, 245, 255)
            # Can't easily box with fpdf2, just use background coloring

        # Common Mistakes
        mistakes = sections.get("common_mistakes", [])
        if mistakes:
            self.section_title("Common Mistakes")
            for m in mistakes:
                self.set_font("DejaVu", "B", 10)
                self.set_text_color(*ACCENT_RED)
                self.cell(0, 6, f"  X {m.get('mistake', '')}", new_x="LMARGIN", new_y="NEXT")
                self.set_font("DejaVu", "I", 10)
                self.set_text_color(*ACCENT_GREEN)
                self.cell(0, 6, f"  OK Fix: {m.get('correction', '')}", new_x="LMARGIN", new_y="NEXT")
                self.ln(3)

        # Summary
        summary = sections.get("summary", [])
        if summary:
            self.section_title("Summary")
            for s in summary:
                self.bullet_point(s)


def get_completed_units():
    """Get list of completed unit directories."""
    units = []
    for f in sorted(glob.glob(f"{CONTENT_DIR}/curriculum/igcse_o/*/")):
        unit_dir = f.rstrip("/")
        name = os.path.basename(unit_dir)
        files = glob.glob(os.path.join(unit_dir, "*.json"))
        if files:
            units.append(name)
    return units


def generate_lesson_plan(unit_name, topics):
    """Generate a lesson plan PDF for a unit."""
    pdf = MathsLMS_PDF()
    pdf.add_page()
    
    title = unit_name.replace("_", " ").title()
    pdf.chapter_title(f"{title} — Lesson Plan", "IGCSE Mathematics 0580 | Concept Guide")
    
    for i, topic_file in enumerate(sorted(topics)):
        with open(topic_file) as f:
            topic = json.load(f)
        
        tid = topic.get("topic_id", f"T{i+1}")
        title = topic.get("title", "")
        
        # Check if we need a new page (don't start on last 1/3 of page)
        if pdf.get_y() > 240:
            pdf.add_page()
        
        pdf.set_font("DejaVu", "B", 14)
        pdf.set_text_color(*PRIMARY)
        pdf.cell(0, 10, f"{tid}: {title}", new_x="LMARGIN", new_y="NEXT")
        pdf.set_draw_color(*SECONDARY)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(4)
        
        pdf.lesson_plan_section(topic)
        
        # GIF reference
        gif_pattern = f"{CONTENT_DIR}/gifs/igcse_o/*{tid.lower()}*"
        gifs = glob.glob(gif_pattern)
        if gifs:
            pdf.ln(2)
            pdf.set_font("DejaVu", "I", 8)
            pdf.set_text_color(150, 150, 160)
            for g in gifs[:2]:
                gname = os.path.basename(g)
                pdf.cell(0, 5, f"Animation: {gname} ({os.path.getsize(g)//1024} KB)", new_x="LMARGIN", new_y="NEXT")
        
        pdf.ln(6)
    
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    path = f"{OUTPUT_DIR}/{unit_name}_lesson-plan.pdf"
    pdf.output(path)
    return path


def generate_worksheet(unit_name, problem_sets):
    """Generate a worksheet PDF (problems only, space for working)."""
    pdf = MathsLMS_PDF()
    pdf.add_page()
    
    title = unit_name.replace("_", " ").title()
    pdf.chapter_title(f"{title} — Worksheet", "IGCSE Mathematics 0580 | Practice Problems")
    
    problem_count = 0
    for ps_file in sorted(problem_sets):
        with open(ps_file) as f:
            ps = json.load(f)
        
        tid = ps.get("topic_id", "")
        ttitle = ps.get("title", "")
        
        pdf.set_font("DejaVu", "B", 12)
        pdf.set_text_color(*PRIMARY)
        pdf.cell(0, 8, f"{tid}: {ttitle}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        
        for prob in ps.get("problems", []):
            if pdf.get_y() > 255:
                pdf.add_page()
            problem_count += 1
            pdf.problem_card(prob, problem_count)
    
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    path = f"{OUTPUT_DIR}/{unit_name}_worksheet.pdf"
    pdf.output(path)
    return {"path": path, "problems": problem_count}


def generate_answer_key(unit_name, problem_sets):
    """Generate an answer key PDF (problems + full solutions)."""
    pdf = MathsLMS_PDF()
    pdf.add_page()
    
    title = unit_name.replace("_", " ").title()
    pdf.chapter_title(f"{title} — Answer Key", "IGCSE Mathematics 0580 | Full Solutions")
    
    problem_count = 0
    for ps_file in sorted(problem_sets):
        with open(ps_file) as f:
            ps = json.load(f)
        
        tid = ps.get("topic_id", "")
        ttitle = ps.get("title", "")
        
        pdf.set_font("DejaVu", "B", 12)
        pdf.set_text_color(*PRIMARY)
        pdf.cell(0, 8, f"{tid}: {ttitle}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)
        
        for prob in ps.get("problems", []):
            if pdf.get_y() > 255:
                pdf.add_page()
            problem_count += 1
            pdf.solution_card(prob, problem_count)
    
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    path = f"{OUTPUT_DIR}/{unit_name}_answer-key.pdf"
    pdf.output(path)
    return {"path": path, "problems": problem_count}


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    if len(sys.argv) > 1:
        target_units = [sys.argv[1]]
    else:
        target_units = get_completed_units()
    
    results = []
    for unit in target_units:
        print(f"\n{'='*60}")
        print(f"  Generating PDFs for: {unit}")
        print(f"{'='*60}")
        
        # Find curriculum files
        cur_dir = f"{CONTENT_DIR}/curriculum/igcse_o/{unit}"
        prob_dir = f"{CONTENT_DIR}/problems/igcse_o/{unit}"
        
        curriculum_files = sorted(glob.glob(f"{cur_dir}/*.json"))
        problem_files = sorted(glob.glob(f"{prob_dir}/*.json"))
        
        if not curriculum_files:
            print(f"  No curriculum files found at {cur_dir}")
            continue
        
        if not problem_files:
            print(f"  No problem files found at {prob_dir}")
            continue
        
        # 1. Lesson Plan
        print(f"  Generating lesson plan...")
        lp_path = generate_lesson_plan(unit, curriculum_files)
        lp_size = os.path.getsize(lp_path) // 1024
        print(f"    Saved: {lp_path} ({lp_size} KB)")
        
        # 2. Worksheet
        print(f"  Generating worksheet...")
        ws_result = generate_worksheet(unit, problem_files)
        ws_size = os.path.getsize(ws_result["path"]) // 1024
        print(f"    Saved: {ws_result['path']} ({ws_result['problems']} problems, {ws_size} KB)")
        
        # 3. Answer Key
        print(f"  Generating answer key...")
        ak_result = generate_answer_key(unit, problem_files)
        ak_size = os.path.getsize(ak_result["path"]) // 1024
        print(f"    Saved: {ak_result['path']} ({ak_result['problems']} solutions, {ak_size} KB)")
        
        results.append({
            "unit": unit,
            "lesson_plan": lp_path,
            "worksheet": ws_result,
            "answer_key": ak_result,
        })
    
    print(f"\n{'='*60}")
    print(f"  COMPLETE: {len(results)} units processed")
    print(f"  PDFs in: {OUTPUT_DIR}")
    print(f"{'='*60}")
    
    # Log to database
    try:
        import sqlite3
        conn = sqlite3.connect(DB_PATH)
        for r in results:
            conn.execute(
                "INSERT INTO content_tasks (track, unit, topic_id, stage, status, agent, notes) VALUES (?, ?, ?, ?, ?, ?, ?)",
                ('igcse_o', r['unit'], 'PDF', 'pdf_generated', 'done', 'Deploy',
                 f"Lesson plan + worksheet + answer key generated")
            )
        conn.execute("INSERT OR REPLACE INTO pipeline_stats (metric, value, updated_at) VALUES (?, ?, datetime('now'))",
                     ('pdfs_generated', len(results)))
        conn.commit()
        conn.close()
    except Exception as e:
        print(f"  DB log warning: {e}")

    return results


if __name__ == "__main__":
    main()
