#!/usr/bin/env python3
"""
Batch generate .md spec files for ALL unprocessed topics programmatically.
Replaces the per-tick cron approach. Processes all 148 topics in one run (~seconds).

Generates LANDSCAPE.md, SOCIAL.md, and ANIMATION_BLUEPRINT.md
for each topic using structured templates based on topic metadata.
"""

import json, os, sys, datetime, re
from pathlib import Path

CONTENT_DIR = "/opt/data/.hermes/content"
CREATIVE_DIR = os.path.join(CONTENT_DIR, "creative")
MANIFEST_PATH = os.path.join(CREATIVE_DIR, "manifest.json")

PALETTE = {
    "bg_deep": "#1A1A2E", "bg_navy": "#0F3460",
    "accent_red": "#E94560", "accent_teal": "#0D7377",
    "accent_gold": "#F5A623", "text_primary": "#E8E8F0", "text_muted": "#8888AA",
}

MASCOTS = {"igcse_o": "Zara", "add_maths": "Zara", "a_level": "Marcus"}

def detect_track(topic_id):
    if topic_id.startswith("AL"): return "a_level"
    if topic_id.startswith("AM"): return "add_maths"
    return "igcse_o"

def first_sentence(text, n=15):
    words = re.split(r"[.!?]", text or "")[0].split()
    return " ".join(words[:n])

def ext(concept_id):
    """Extract unit code from topic_id e.g. AL3_Q1 -> AL3"""
    return concept_id.split("_")[0] if "_" in concept_id else concept_id[:3]

# ─── LANDSCAPE.md generator ──────────────────────────────────────────

def gen_landscape(topic):
    tid = topic["topic_id"]
    title = topic["title"]
    track = detect_track(tid)
    hook = topic.get("hook", "")
    steps = topic.get("worked_example", "")
    mascot = MASCOTS.get(track, "Zara")

    hook_line = first_sentence(hook, 8) or "Explore this mathematical concept"
    step_list = []
    if isinstance(steps, dict):
        step_list = [steps.get("question", "")[:80]] if "question" in steps else []
    elif isinstance(steps, str):
        step_list = [s.strip() for s in steps.split("\n") if s.strip().startswith("**Step")][:4]

    tl = track.replace("_", " ").title()

    return f"""# LANDSCAPE — {title}
**Format:** 16:9 (1920×1080px)
**Track:** {tl} — {mascot}
**Palette:** MathsLMS Dark

---

## PANEL 1 — HOOK (Left 30%, 576×1080px)

**Background:** `{PALETTE["accent_gold"]}` with 15% opacity dot grid
**Mascot:** {mascot} (180px), bottom-left corner
**Headline:** "{hook_line}"
**Sub-line:** `Used in: {topic.get("syllabus_ref", "mathematics")}`
**Visual:** Concept icon representing "{ext(tid)}"

---

## PANEL 2 — DEFINITION (Centre 40%, top half, 768×540px)

**Background:** `{PALETTE["bg_navy"]}`
**Title:** {title} (Inter Tight Bold, 36px, {PALETTE["text_primary"]})
**Definition:** {hook_line}
**Prerequisite chips:** up to 3 pill tags in `{PALETTE["accent_red"]}`

---

## PANEL 3 — WORKED EXAMPLE (Centre 40%, bottom half, 768×540px)

**Background:** `{PALETTE["bg_deep"]}` with subtle grid
**Steps:"""
    for i, s in enumerate(step_list[:4], 1):
        clean = s.replace("**", "").strip()[:80]
        if clean:
            s += f"""
  - Step {i}: `{clean}` (annotation in {PALETTE["text_muted"]})"""
    if not step_list:
        s += """
  - Step 1: Setup — identify given information
  - Step 2: Apply — use the relevant formula or theorem
  - Step 3: Simplify — combine like terms and reduce
  - Step 4: Conclude — state the final answer"""
    s += f"""
**Final answer box:** `{PALETTE["accent_teal"]}` border, bold

---

## PANEL 4 — KEY FACTS (Right 30%, 576×1080px)

**Background:** `{PALETTE["bg_deep"]}` with right-edge 8px `{PALETTE["accent_red"]}` stripe
**Facts:**
  - 🔍 {title} is fundamental to {tl} mathematics
  - 📐 Appears in past papers across all exam boards
  - ⚡ Links to {topic.get("prerequisites", "prior topics")}
**Common mistake:** Watch for sign errors and misapplied formulas.

---

*Generated by CreativeTeacher · MathsLMS · {datetime.date.today().isoformat()}*
"""

# ─── SOCIAL.md generator ────────────────────────────────────────────

def gen_social(topic):
    tid = topic["topic_id"]
    title = topic["title"]
    track = detect_track(tid)
    hook = topic.get("hook", "")
    mascot = MASCOTS.get(track, "Zara")
    tl = track.replace("_", " ").title()

    hook_q = first_sentence(hook, 6) + "?"
    if not hook_q.strip("?"):
        hook_q = f"Can you master {ext(tid)}?"

    return f"""# SOCIAL — {title}
**Format:** 9:16 (1080×1920px)
**Track:** {tl} — {mascot}
**Palette:** MathsLMS Dark

---

## SECTION 1 — HOOK FRAME (Top 25%, 1080×480px)

**Background:** Full-width `{PALETTE["accent_gold"]}` band
**Mascot:** {mascot} (120px, top-right)
**Hook question:** "{hook_q}"

---

## SECTION 2 — CONCEPT SNAP (25%, 1080×480px)

**Background:** `{PALETTE["bg_navy"]}`
**Title:** {title} (Inter Tight Bold, 44px)
**Summary:** Core concept from {tl} mathematics

---

## SECTION 3 — STEP STRIP (30%, 1080×576px)

**Background:** `{PALETTE["bg_deep"]}`
**Steps (3 most critical):**
  - Step 1 — Identify what's given (left border: `{PALETTE["accent_red"]}`)
  - Step 2 — Apply the method (left border: `{PALETTE["accent_teal"]}`)
  - Step 3 — State the result (left border: `{PALETTE["accent_gold"]}`)
**Caption:** "Swipe for full solution →" in {PALETTE["text_muted"]}

---

## SECTION 4 — CTA FOOTER (20%, 1080×384px)

**Background:** `{PALETTE["bg_navy"]}`
**Track badge:** `{tl}` pill
**CTA:** "Practice this on MathsLMS" (Inter Tight Bold)
**QR placeholder:** 32×32px box

---

*Generated by CreativeTeacher · MathsLMS · {datetime.date.today().isoformat()}*
"""

# ─── ANIMATION_BLUEPRINT.md generator ───────────────────────────────

def gen_animation(topic):
    tid = topic["topic_id"]
    title = topic["title"]
    track = detect_track(tid)
    mascot = MASCOTS.get(track, "Marcus" if track == "a_level" else "Zara")
    hook = topic.get("hook", "")
    hook_visual = first_sentence(hook, 12) or f"Visual introduction to {title}"

    frames = [
        ("0–2s", f"Opening — {title} scene", "Hook the learner with real-world context"),
        ("2–4s", f"Key definition or formula reveal", "Establish mathematical foundation"),
        ("4–6s", f"Step-by-step worked example", "Build procedural understanding"),
        ("6–8s", f"Critical transformation or insight", "Deepen conceptual grasp"),
        ("8–10s", f"Result and summary", "Solidify and conclude"),
    ]

    frame_table = "\n".join(f"  | {i+1} | {t} | {v} | {p} |" for i, (t, v, p) in enumerate(frames))

    track_label = track.replace("_", " ").title()

    return f"""# Animation Blueprint — {title}

**Topic ID:** {tid}
**Track:** {track_label}
**Mascot:** {mascot}

---

## SECTION 1 — CREATIVE BRIEF

**METAPHOR:** Step-by-step visual walkthrough of {title.lower()}, building from foundation to mastery.
**CHARACTER:** {mascot} ({track_label}) — guides the learner through each stage.
**PALETTE:** MathsLMS Dark ({PALETTE["bg_deep"]} bg, {PALETTE["accent_red"]} accent, {PALETTE["accent_teal"]} success, {PALETTE["accent_gold"]} highlight).
**TONE:** {"Precise and analytical" if track == "a_level" else "Curious and encouraging"}.
**HOOK_VISUAL:** {hook_visual}
**KEY_TRANSITION:** Step 3 → Step 4 — the critical procedural leap.

---

## SECTION 2 — GIF ANIMATION BRIEF

| Field | Value |
|-------|-------|
| concept_id | {tid} |
| title | {title} |
| duration_target | 10 seconds |
| loop_behaviour | 4-sec loop, pause 1s at step 4 |
| file_size_target_kb | ≤500 KB |
| resolution | 800×450px, 15fps max |
| palette | bg `{PALETTE["bg_deep"]}`, primary `{PALETTE["accent_red"]}`, secondary `{PALETTE["accent_teal"]}` |

### FRAME SEQUENCE

| Frame | Time | Visual | Pedagogical Purpose |
|-------|------|--------|---------------------|
{frame_table}

**SPECIAL_EFFECTS:** Smooth transitions between frames, highlight key terms in {PALETTE["accent_gold"]}
**MANIM_SCENE_HINTS:** Use Write for text reveals, Transform for equation morphing

---

## SECTION 3 — FORMAT IMPLEMENTATION NOTES

**MANIM NOTES:**
- Scene structure: one scene per frame group, sequential playback
- Key mobjects: Title, Formula, StepBox, ResultBox
- Use {PALETTE["accent_red"]} for important elements, {PALETTE["accent_teal"]} for correct answers

**CANVAS JS NOTES:**
- Step structure: 5 steps matching the frame sequence above
- Colour coding: blue for setup, orange for manipulation, green for result
- Controls: Prev/Next/Auto with step counter

**CSS ANIMATION NOTES:**
- @keyframes for each step reveal with staggered animation-delay
- Dark background (#1A1A2E), accent highlights
- Print stylesheet included for accessibility

**ASCII FRAME NOTES:**
- 50×20 box-drawing panels per frame
- Frame title top-centre, step label, equation in plain-text
- ┌ ─ ┐ │ └ ┘ borders, ∎ for final frame

---

*Generated by CreativeTeacher · MathsLMS · {datetime.date.today().isoformat()}*
"""


# ─── Main batch process ─────────────────────────────────────────────

def load_manifest():
    if os.path.isfile(MANIFEST_PATH):
        with open(MANIFEST_PATH) as f:
            return json.load(f)
    return {"description": "Creative asset outputs", "skills": ["infographic-architect", "animation-blueprint"], "concepts": []}

def save_manifest(m):
    os.makedirs(os.path.dirname(MANIFEST_PATH), exist_ok=True)
    with open(MANIFEST_PATH, "w") as f:
        json.dump(m, f, indent=2)

def scan_topics():
    topics = []
    for root, dirs, files in os.walk(os.path.join(CONTENT_DIR, "curriculum")):
        for fn in sorted(files):
            if not fn.endswith(".json") or "_problems" in fn or fn.startswith("."):
                continue
            fp = os.path.join(root, fn)
            with open(fp) as f:
                try:
                    data = json.load(f)
                except:
                    continue
            tid = data.get("topic_id", "")
            if not tid:
                continue
            sections = data.get("sections", {})
            topics.append({
                "topic_id": tid,
                "title": data.get("title", ""),
                "track": data.get("track", detect_track(tid)),
                "path": fp,
                "hook": sections.get("hook", ""),
                "prerequisites": sections.get("prerequisites", ""),
                "worked_example": sections.get("worked_example", ""),
                "syllabus_ref": data.get("syllabus_ref", ""),
            })
    return topics

def main():
    manifest = load_manifest()
    done_ids = {c["concept_id"] for c in manifest.get("concepts", [])}
    topics = scan_topics()
    pending = [t for t in topics if t["topic_id"] not in done_ids]
    total = len(topics)
    done = len(done_ids)

    print(f"📊 {done}/{total} already generated, {len(pending)} pending")
    if not pending:
        print("✅ All topics done!")
        return

    count = 0
    errors = []
    for topic in pending:
        tid = topic["topic_id"]
        out_dir = os.path.join(CREATIVE_DIR, tid)
        os.makedirs(out_dir, exist_ok=True)

        try:
            # Generate all 3 specs
            landscape = gen_landscape(topic)
            with open(os.path.join(out_dir, "LANDSCAPE.md"), "w") as f:
                f.write(landscape)

            social = gen_social(topic)
            with open(os.path.join(out_dir, "SOCIAL.md"), "w") as f:
                f.write(social)

            anim = gen_animation(topic)
            with open(os.path.join(out_dir, "ANIMATION_BLUEPRINT.md"), "w") as f:
                f.write(anim)

            # Update manifest
            manifest["concepts"].append({
                "concept_id": tid,
                "generated_at": datetime.datetime.now().isoformat(),
                "files": ["LANDSCAPE.md", "SOCIAL.md", "ANIMATION_BLUEPRINT.md"],
            })
            save_manifest(manifest)

            count += 1
            if count % 10 == 0:
                print(f"  {done+count}/{total} — {tid}")
                sys.stdout.flush()

        except Exception as e:
            errors.append(f"{tid}: {e}")
            print(f"  ❌ {tid}: {e}")

    print(f"\n✅ Generated {count} topic spec sets")
    if errors:
        print(f"⚠  {len(errors)} errors:\n" + "\n".join(errors[:5]))
    if errors:
        sys.exit(1)

if __name__ == "__main__":
    main()
