#!/usr/bin/env python3
"""
Batch generate .md spec files for ALL topics.
Extracts REAL content from curriculum JSONs — worked examples, mistakes, prerequisites.
"""

import json, os, sys, datetime, re
from pathlib import Path

CONTENT_DIR = "/opt/data/.hermes/content"
CREATIVE_DIR = os.path.join(CONTENT_DIR, "creative")
MANIFEST_PATH = os.path.join(CREATIVE_DIR, "manifest.json")

PALETTE = {"bg_deep": "#1A1A2E", "bg_navy": "#0F3460", "accent_red": "#E94560",
           "accent_teal": "#0D7377", "accent_gold": "#F5A623", "text_primary": "#E8E8F0", "text_muted": "#8888AA"}
MASCOTS = {"igcse_o": "Zara", "add_maths": "Zara", "a_level": "Marcus"}

def detect_track(tid):
    if tid.startswith("AL"): return "a_level"
    if tid.startswith("AM"): return "add_maths"
    return "igcse_o"

def strip_img(t):
    return re.sub(r'\[img:[^\]]+\]\s*', '', t or "").strip()

def first_real_sentence(t, n=18):
    t = strip_img(t)
    s = re.split(r'[.!?]', t)[0].strip()
    words = s.split()
    return " ".join(words[:n])

def clean_latex(t):
    """Replace LaTeX with plain text approximations."""
    t = re.sub(r'\$([^$]+)\$', r'\1', t)
    t = t.replace("\\\\", "\\").replace("\\mathbb{N}", "N").replace("\\mathbb{Z}", "Z")
    t = t.replace("\\mathbb{Q}", "Q").replace("\\mathbb{R}", "R")
    t = re.sub(r'\\[a-z]+', '', t)
    return t.strip()

def extract_steps_from_we(we):
    """Extract step descriptions from worked_example (string or dict)."""
    if isinstance(we, dict):
        text = we.get("question", "") + "\n" + we.get("solution", "")
    else:
        text = we or ""
    steps = []
    lines = text.split("\n")
    for line in lines:
        line = line.strip()
        if re.match(r'^\d+[.)]\s', line):
            steps.append(clean_latex(re.sub(r'^\d+[.)]\s*', '', line))[:100])
        elif line.startswith("**Step") or re.match(r'^Step\s+\d+', line):
            steps.append(clean_latex(re.sub(r'^\*\*Step\s+\d+[:\s]*\*\*', '', line))[:100])
    if not steps:
        steps = ["Classify each number by type", "Apply the definition of each set", "State all sets that apply"]
    return steps[:5]

def fmt_we_steps(steps):
    return "\n".join(f"  - Step {i+1}: {s}" for i, s in enumerate(steps))

# ─── LANDSCAPE.md ───────────────────────────────────────────────────

def gen_landscape(topic):
    tid, title, track, hook = topic["topic_id"], topic["title"], detect_track(topic["topic_id"]), topic.get("hook","")
    we_steps = extract_steps_from_we(topic.get("worked_example",""))
    mistakes = topic.get("common_mistakes", [])
    prereqs = topic.get("prerequisites", [])
    summary = topic.get("summary", [])
    mascot = MASCOTS.get(track, "Zara")
    tl = track.replace("_"," ").title()
    hook_line = first_real_sentence(hook, 10) or f"Explore {title}"

    fact1 = clean_latex(summary[0]) if summary else f"{title} is fundamental mathematics"
    fact2 = clean_latex(summary[1]) if len(summary) > 1 else "Key concept for exam success"
    fact3 = clean_latex( summary[2]) if len(summary) > 2 else "Builds on prior knowledge"

    cm_text = ""
    if mistakes and isinstance(mistakes[0], dict):
        cm_text = strip_img(mistakes[0].get("mistake", ""))[:120]
    elif mistakes and isinstance(mistakes[0], str):
        cm_text = strip_img(mistakes[0])[:120]
    if not cm_text:
        cm_text = "Watch for common errors in classification and computation."

    prereq_text = ", ".join(clean_latex(p)[:40] for p in prereqs[:3]) if prereqs else "Foundational mathematics"

    return f"""# LANDSCAPE — {title}
**Format:** 16:9 (1920×1080px)
**Track:** {tl} — {mascot}
**Palette:** MathsLMS Dark

---

## PANEL 1 — HOOK (Left 30%, 576×1080px)

**Background:** `{PALETTE["accent_gold"]}` with 15% opacity dot grid
**Mascot:** {mascot} (180px), bottom-left corner
**Headline:** "{hook_line}"
**Sub-line:** `Used in: {topic.get("syllabus_ref", "mathematics")}`
**Visual:** Concept icon representing "{tid[:3]}"

---

## PANEL 2 — DEFINITION (Centre 40%, top half, 768×540px)

**Background:** `{PALETTE["bg_navy"]}`
**Title:** {title} (Inter Tight Bold, 36px, {PALETTE["text_primary"]})
**Definition:** {first_real_sentence(hook, 15) or title}
**Prerequisite chips:** {prereq_text}

---

## PANEL 3 — WORKED EXAMPLE (Centre 40%, bottom half, 768×540px)

**Background:** `{PALETTE["bg_deep"]}` with subtle grid
**Steps:**
{fmt_we_steps(we_steps)}
**Final answer box:** `{PALETTE["accent_teal"]}` border, bold

---

## PANEL 4 — KEY FACTS (Right 30%, 576×1080px)

**Background:** `{PALETTE["bg_deep"]}` with right-edge 8px `{PALETTE["accent_red"]}` stripe
**Facts:**
  - 🔍 {fact1}
  - 📐 {fact2}
  - ⚡ {fact3}
**Common mistake:** {cm_text}

---

*Generated by CreativeTeacher · MathsLMS · {datetime.date.today().isoformat()}*
"""

# ─── SOCIAL.md ──────────────────────────────────────────────────────

def gen_social(topic):
    tid, title, track, hook = topic["topic_id"], topic["title"], detect_track(topic["topic_id"]), topic.get("hook","")
    we_steps = extract_steps_from_we(topic.get("worked_example",""))
    mascot = MASCOTS.get(track, "Zara")
    tl = track.replace("_"," ").title()

    hook_q = first_real_sentence(hook, 8).rstrip("?") + "?"
    if not hook_q.strip("?"):
        hook_q = f"Can you master {title}?"

    return f"""# SOCIAL — {title}
**Format:** 9:16 (1080×1920px)
**Track:** {tl} — {mascot}
**Palette:** MathsLMS Dark

---

## SECTION 1 — HOOK FRAME (Top 25%, 1080×480px)

**Background:** Full-width `{PALETTE["accent_gold"]}` band
**Mascot:** {mascot} (120px, top-right)
**Hook question:** "{hook_q}"

---

## SECTION 2 — CONCEPT SNAP (25%, 1080×480px)

**Background:** `{PALETTE["bg_navy"]}`
**Title:** {title} (Inter Tight Bold, 44px)
**Summary:** {first_real_sentence(hook, 6) or "Core concept"}

---

## SECTION 3 — STEP STRIP (30%, 1080×576px)

**Background:** `{PALETTE["bg_deep"]}`
**Steps (3 most critical):**
  - Step 1 — {we_steps[0] if len(we_steps) > 0 else "Identify what's given"} (left border: `{PALETTE["accent_red"]}`)
  - Step 2 — {we_steps[1] if len(we_steps) > 1 else "Apply the method"} (left border: `{PALETTE["accent_teal"]}`)
  - Step 3 — {we_steps[2] if len(we_steps) > 2 else "State the result"} (left border: `{PALETTE["accent_gold"]}`)
**Caption:** "Swipe for full solution →" in {PALETTE["text_muted"]}

---

## SECTION 4 — CTA FOOTER (20%, 1080×384px)

**Background:** `{PALETTE["bg_navy"]}`
**Track badge:** `{tl}` pill
**CTA:** "Practice this on MathsLMS" (Inter Tight Bold)
**QR placeholder:** 32×32px box

---

*Generated by CreativeTeacher · MathsLMS · {datetime.date.today().isoformat()}*
"""

# ─── ANIMATION_BLUEPRINT.md ─────────────────────────────────────────

def gen_animation(topic):
    tid, title, track, hook = topic["topic_id"], topic["title"], detect_track(topic["topic_id"]), topic.get("hook","")
    we_steps = extract_steps_from_we(topic.get("worked_example",""))
    mistakes = topic.get("common_mistakes", [])
    mascot = MASCOTS.get(track, "Marcus" if track == "a_level" else "Zara")
    tl = track.replace("_"," ").title()

    hook_visual = first_real_sentence(hook, 12) or f"Visual introduction to {title}"
    cm_hint = ""
    if mistakes and isinstance(mistakes[0], dict):
        cm_hint = strip_img(mistakes[0].get("mistake",""))[:80]
    elif mistakes and isinstance(mistakes[0], str):
        cm_hint = strip_img(mistakes[0])[:80]

    step_count = len(we_steps)
    hook_half = first_real_sentence(hook, 8) or f"Explore {title}"
    frames = []
    # Frame 1: hook visual
    frames.append((1, "0–2s", hook_half, "Hook the learner with a real-world context"))
    # Middle frames: contextualized steps (skip empty)
    for i, s in enumerate(we_steps[:4]):
        if not s.strip(): continue
        purpose = ["Establish the mathematical foundation",
                   "Build procedural understanding step by step",
                   "Deepen conceptual grasp with practice",
                   "Solidify understanding before moving on"][min(i, 3)]
        time_start = (i+1)*2
        desc = f"Work through: {clean_latex(s)[:70]}"
        frames.append((i+2, f"{time_start}–{time_start+2}s", desc, purpose))
    # If no real steps, use generic frames
    if len(frames) <= 1:
        frames = [(1, "0–2s", f"Introduce {title} visually", "Hook the learner with context"),
                  (2, "2–4s", "Present the key definition", "Build foundation"),
                  (3, "4–6s", "Work through a detailed example", "Develop understanding"),
                  (4, "6–8s", "Highlight the critical insight", "Deepen grasp"),
                  (5, "8–10s", f"Summarise {title}", "Conclude and connect")]

    frame_table = "\n".join(f"  | {n} | {t} | {v} | {p} |" for n, t, v, p in frames)
    effect_hint = f"Highlight common pitfall: {cm_hint[:60]}" if cm_hint else "Smooth transitions between frames, highlight key terms"

    return f"""# Animation Blueprint — {title}

**Topic ID:** {tid}
**Track:** {tl}
**Mascot:** {mascot}

---

## SECTION 1 — CREATIVE BRIEF

**METAPHOR:** Step-by-step visual exploration of {title.lower()}, grounded in real mathematical practice.
**CHARACTER:** {mascot} ({tl}) — guides the learner through each stage.
**PALETTE:** MathsLMS Dark ({PALETTE["bg_deep"]} bg, {PALETTE["accent_red"]} accent, {PALETTE["accent_teal"]} success, {PALETTE["accent_gold"]} highlight).
**TONE:** {"Precise and analytical" if track == "a_level" else "Curious and encouraging"}.
**HOOK_VISUAL:** {hook_visual}
**KEY_TRANSITION:** The step from definition to application — the most critical conceptual leap.

---

## SECTION 2 — GIF ANIMATION BRIEF

| Field | Value |
|-------|-------|
| concept_id | {tid} |
| title | {title} |
| duration_target | {max(len(frames)*2, 8)} seconds |
| loop_behaviour | 4-sec loop, pause 1s at key transition |
| file_size_target_kb | ≤500 KB |
| resolution | 800×450px, 15fps max |
| palette | bg `{PALETTE["bg_deep"]}`, primary `{PALETTE["accent_red"]}`, secondary `{PALETTE["accent_teal"]}` |

### FRAME SEQUENCE

| Frame | Time | Visual | Pedagogical Purpose |
|-------|------|--------|---------------------|
{frame_table}

**SPECIAL_EFFECTS:** {effect_hint}
**MANIM_SCENE_HINTS:** Use Write for text reveals, Transform for equation morphing, highlight key terms in {PALETTE["accent_gold"]}

---

## SECTION 3 — FORMAT IMPLEMENTATION NOTES

**MANIM NOTES:**
- Scene structure: one scene per frame group, sequential playback
- Key mobjects: Title, Formula, StepBox, ResultBox
- Use {PALETTE["accent_red"]} for important elements, {PALETTE["accent_teal"]} for correct answers

**CANVAS JS NOTES:**
- Step structure: {len(frames)} steps matching the frame sequence above
- Colour coding: blue for setup, orange for manipulation, green for result
- Controls: Prev/Next/Auto with step counter

**CSS ANIMATION NOTES:**
- @keyframes for each step reveal with staggered animation-delay
- Dark background ({PALETTE["bg_deep"]}), accent highlights
- Print stylesheet included for accessibility

**ASCII FRAME NOTES:**
- 50×20 box-drawing panels per frame
- Frame title top-centre, step label, equation in plain-text
- ┌ ─ ┐ │ └ ┘ borders, ∎ for final frame

---

*Generated by CreativeTeacher · MathsLMS · {datetime.date.today().isoformat()}*
"""


# ─── Main ───────────────────────────────────────────────────────────

def scan_topics():
    topics = []
    for root, dirs, files in os.walk(os.path.join(CONTENT_DIR, "curriculum")):
        for fn in sorted(files):
            if not fn.endswith(".json") or "_problems" in fn or fn.startswith("."):
                continue
            fp = os.path.join(root, fn)
            with open(fp) as f:
                try:
                    data = json.load(f)
                except:
                    continue
            tid = data.get("topic_id", "")
            if not tid:
                continue
            s = data.get("sections", {})
            topics.append({
                "topic_id": tid,
                "title": data.get("title", ""),
                "path": fp,
                "hook": s.get("hook", ""),
                "prerequisites": s.get("prerequisites", []),
                "worked_example": s.get("worked_example", ""),
                "common_mistakes": s.get("common_mistakes", []),
                "summary": s.get("summary", []),
                "syllabus_ref": data.get("syllabus_ref", ""),
            })
    return topics

def load_manifest():
    if os.path.isfile(MANIFEST_PATH):
        with open(MANIFEST_PATH) as f:
            return json.load(f)
    return {"description": "Creative asset outputs", "skills": ["infographic-architect", "animation-blueprint"], "concepts": []}

def save_manifest(m):
    os.makedirs(CREATIVE_DIR, exist_ok=True)
    with open(MANIFEST_PATH, "w") as f:
        json.dump(m, f, indent=2)

def main():
    manifest = load_manifest()
    done_ids = {c["concept_id"] for c in manifest.get("concepts", [])}
    topics = scan_topics()
    pending = [t for t in topics if t["topic_id"] not in done_ids]
    total = len(topics)
    done = len(done_ids)

    # If some exist but with old generic spec, re-process them all
    force = "--force" in sys.argv
    if force:
        pending = topics
        manifest["concepts"] = []
        print("🔁 Force mode: regenerating all specs")

    print(f"📊 {done}/{total} existing, {len(pending)} to generate")
    count = 0
    errors = []

    for topic in pending:
        tid = topic["topic_id"]
        out_dir = os.path.join(CREATIVE_DIR, tid)
        os.makedirs(out_dir, exist_ok=True)

        try:
            with open(os.path.join(out_dir, "LANDSCAPE.md"), "w") as f:
                f.write(gen_landscape(topic))
            with open(os.path.join(out_dir, "SOCIAL.md"), "w") as f:
                f.write(gen_social(topic))
            with open(os.path.join(out_dir, "ANIMATION_BLUEPRINT.md"), "w") as f:
                f.write(gen_animation(topic))

            manifest["concepts"].append({
                "concept_id": tid,
                "generated_at": datetime.datetime.now().isoformat(),
                "files": ["LANDSCAPE.md", "SOCIAL.md", "ANIMATION_BLUEPRINT.md"],
            })
            count += 1
            if count % 15 == 0:
                save_manifest(manifest)
                print(f"  {done+count}/{total} — {tid}")
                sys.stdout.flush()

        except Exception as e:
            errors.append(f"{tid}: {e}")
            print(f"  ❌ {tid}: {e}")

    save_manifest(manifest)
    print(f"\n✅ Generated {count} topic spec sets")
    if errors:
        print(f"⚠  {len(errors)} errors:" + "\n".join(errors[:5]))
        sys.exit(1 if errors else 0)

if __name__ == "__main__":
    main()
